import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
=======
import { AuthProvider } from "./context/AuthContext";

>>>>>>> 6e334ba246ab83a591f58daec68cfdca197e79e3
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Task Pilot",
  description: "A student task managing app",
>>>>>>> 6e334ba246ab83a591f58daec68cfdca197e79e3
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">{children}</body>
=======
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
>>>>>>> 6e334ba246ab83a591f58daec68cfdca197e79e3
    </html>
  );
}
